"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=Csv(),
)

# Orígenes desde los que se aceptan peticiones POST. Solo hace falta cuando la
# aplicación se sirve tras un proxy o un túnel HTTPS: sin declararlo, Django
# rechaza el envío de cualquier formulario por comprobación de CSRF.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=Csv(),
)

# Desplegada tras un proxy que termina el HTTPS, la petición llega a Django
# por HTTP y el proxy avisa con esta cabecera. Sin ella, build_absolute_uri
# daría direcciones http:// y el QR del RF-08 apuntaría a un esquema que el
# proxy redirige. La cabecera solo es fiable si nadie puede saltarse el
# proxy: el servidor de aplicación debe escuchar solo en localhost.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Con SOLO_HTTPS=True el navegador no envía la cookie de sesión ni la de CSRF
# por HTTP en claro. Se controla por variable y no se ata a DEBUG para poder
# probar con DEBUG=False en local, donde no hay HTTPS.
SOLO_HTTPS = config('SOLO_HTTPS', default=False, cast=bool)
SESSION_COOKIE_SECURE = SOLO_HTTPS
CSRF_COOKIE_SECURE = SOLO_HTTPS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'evaluaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sirve los estáticos reunidos en STATIC_ROOT desde el propio proceso, que
    # es lo que Django deja de hacer con DEBUG=False. Va justo después del de
    # seguridad, como indica la documentación de whitenoise.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Exige sesión en toda la aplicación en vez de decorar vista por vista:
    # así una vista nueva nace protegida y las excepciones, como la consulta
    # anónima del RF-09, se marcan con @login_not_required a la vista de
    # quien lea el código. Va después de AuthenticationMiddleware, que es
    # quien deja el request.user que este consulta.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Entrada y salida de la aplicación

# Destino al que el middleware desvía a quien no tiene sesión. Se indica por
# nombre de ruta y no por dirección escrita a mano: por defecto valdría
# /accounts/login/, que en este proyecto no existe.
LOGIN_URL = 'login'

# Dónde se aterriza al entrar cuando no se venía desviado de otra página.
LOGIN_REDIRECT_URL = 'evaluaciones:inicio'

# Al salir se vuelve a la entrada: llevar a la portada sería rebotar de nuevo
# hasta aquí, porque también exige sesión.
LOGOUT_REDIRECT_URL = 'login'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde `collectstatic` reúne los estáticos de todas las apps para
# servirlos en despliegue. Se genera, no se versiona (está en el .gitignore).
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Ficheros subidos por el usuario: la documentación de los equipos (RF-09).
# Se separan de los estáticos a propósito. Los estáticos son parte del
# programa y viajan con él; estos los sube quien usa la aplicación, cambian
# sin que nadie despliegue nada y por eso no se versionan: media/ está en el
# .gitignore. En desarrollo los sirve Django (ver config/urls.py); en
# producción tendría que servirlos el servidor web.

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
