# Generated by Django 5.2.16 on 2026-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
