# Generated by Django 5.2.16 on 2026-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_equipo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='evaluaciones.tipoequipo'),
        ),
        migrations.AddField(
            model_name='grupocriterio',
            name='tipos_aplicables',
            field=models.ManyToManyField(blank=True, help_text='Tipos de equipo a los que aplica este grupo. Sin ninguno, aplica a todos los equipos.', related_name='grupos', to='evaluaciones.tipoequipo'),
        ),
    ]
