# Generated by Django 5.2.16 on 2026-07-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_tipoequipo_equipo_tipos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='grupocriterio',
            options={'ordering': ['orden'], 'verbose_name': 'Grupo de criterios', 'verbose_name_plural': 'Grupos de criterios'},
        ),
        migrations.AlterModelOptions(
            name='linea',
            options={'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
        migrations.AlterModelOptions(
            name='tipoequipo',
            options={'verbose_name': 'Tipo de equipo', 'verbose_name_plural': 'Tipos de equipo'},
        ),
        migrations.AlterField(
            model_name='equipo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='evaluaciones.linea', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marca / modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='num_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nº de serie'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='evaluaciones.tipoequipo', verbose_name='Tipos de equipo'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='en_revision',
            field=models.BooleanField(default=False, verbose_name='En revisión'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
    ]
