# Generated by Django 5.2.16 on 2026-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_alter_evaluacion_options_alter_grupocriterio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tipos_confirmados',
            field=models.BooleanField(default=False, help_text='Alguien ha revisado a qué tipos del Anexo I.2 pertenece el equipo. Distingue un equipo que no es de ninguno de otro cuyo tipo todavía no se ha comprobado.', verbose_name='Tipos confirmados'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipos',
            field=models.ManyToManyField(blank=True, help_text='Marque todos los que apliquen; un mismo equipo puede ser de varios tipos. Si no es de ninguno, déjelo sin marcar.', related_name='equipos', to='evaluaciones.tipoequipo', verbose_name='Tipos de equipo'),
        ),
    ]
