# Generated by Django 5.2.16 on 2026-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_equipo_tipos_confirmados_alter_equipo_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipos',
            field=models.ManyToManyField(blank=True, help_text='Marque todos los que apliquen; un mismo equipo puede ser de varios tipos. Si no es de ninguno, déjelo sin marcar.', related_name='equipos', to='evaluaciones.tipoequipo', verbose_name='Tipos de equipo'),
        ),
    ]
