# Generated by Django 5.2.16 on 2026-08-18 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_equipo_tipos_confirmados_alter_equipo_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de alta')),
                ('fecha_prevista', models.DateField(blank=True, null=True, verbose_name='Fecha prevista')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('EC', 'En curso'), ('R', 'Realizada'), ('D', 'Descartada')], default='P', max_length=2)),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='evaluaciones.evaluacion')),
                ('no_conformidades', models.ManyToManyField(related_name='medidas', to='evaluaciones.respuesta', verbose_name='No conformidades')),
            ],
            options={
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
