# Generated by Django 5.2.16 on 2026-08-19 15:10

import django.db.models.deletion
import django.utils.timezone
import evaluaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MF', 'Manual o instrucciones del fabricante'), ('IU', 'Información de utilización segura'), ('CE', 'Declaración CE de conformidad'), ('RC', 'Registro de comprobación'), ('OT', 'Otro')], max_length=2)),
                ('tipo_otro', models.CharField(blank=True, max_length=100, verbose_name='Especifique el tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fichero', models.FileField(upload_to=evaluaciones.models.ruta_documento, verbose_name='Fichero')),
                ('publico', models.BooleanField(default=False, help_text='Marque los documentos que deben estar a disposición de los trabajadores: cualquiera que escanee el código QR del equipo podrá abrirlos sin identificarse.', verbose_name='Visible sin autenticar')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de subida')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='evaluaciones.equipo')),
            ],
            options={
                'ordering': ['tipo', '-fecha_subida'],
            },
        ),
    ]
