# Generated by Django 5.2.16 on 2026-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-publico', 'tipo', '-fecha_subida']},
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
    ]
