# Generated by Django 5.2.16 on 2026-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_equipo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('MF', 'Manual o instrucciones del fabricante'), ('IU', 'Información de utilización segura'), ('CE', 'Declaración CE de conformidad'), ('RC', 'Registro de comprobación'), ('RM', 'Registro de mantenimiento'), ('OT', 'Otro')], max_length=2),
        ),
    ]
