# Generated by Django 5.2.16 on 2026-08-19 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0011_criterio_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExencionDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IU', 'Información de utilización segura'), ('RC', 'Registro de comprobación'), ('RM', 'Registro de mantenimiento'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo de documento')),
                ('motivo', models.TextField(help_text='Por qué no procede en este equipo. Queda a la vista en la ficha, así que escríbalo como lo defendería ante una inspección.', verbose_name='Motivo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exenciones', to='evaluaciones.equipo')),
            ],
            options={
                'verbose_name': 'Exención documental',
                'verbose_name_plural': 'Exenciones documentales',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('equipo', 'tipo'), name='unique_exencion_por_tipo_en_equipo')],
            },
        ),
    ]
