# Generated by Django 5.2.16 on 2026-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0012_exenciondocumental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('MF', 'Manual o instrucciones del fabricante'), ('IU', 'Información de utilización segura'), ('CE', 'Declaración CE de conformidad'), ('MC', 'Fotografía del marcado CE o placa de características'), ('RC', 'Registro de comprobación'), ('RM', 'Registro de mantenimiento'), ('OT', 'Otro')], help_text='Vacío si este criterio no se acredita con un documento.', max_length=2, verbose_name='Documento que lo acredita'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('MF', 'Manual o instrucciones del fabricante'), ('IU', 'Información de utilización segura'), ('CE', 'Declaración CE de conformidad'), ('MC', 'Fotografía del marcado CE o placa de características'), ('RC', 'Registro de comprobación'), ('RM', 'Registro de mantenimiento'), ('OT', 'Otro')], max_length=2),
        ),
    ]
