# Generated by Django 5.2.16 on 2026-08-19 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def motivo_de_las_ya_marcadas(apps, schema_editor):
    """Las evaluaciones ya en revisión lo están por cambio de tipos.

    Hasta esta migración era la única causa posible, así que el motivo se
    puede deducir sin preguntar. Sin esto se quedarían con el motivo vacío y
    la etiqueta caería al genérico «En revisión».
    """
    Evaluacion = apps.get_model('evaluaciones', 'Evaluacion')
    Evaluacion.objects.filter(en_revision=True, motivo_revision='').update(
        motivo_revision='T',
    )


def sin_motivo(apps, schema_editor):
    Evaluacion = apps.get_model('evaluaciones', 'Evaluacion')
    Evaluacion.objects.update(motivo_revision='')


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0014_evidenciaesperada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='motivo_revision',
            field=models.CharField(blank=True, choices=[('T', 'Desfasada'), ('I', 'Con incidencia')], max_length=1, verbose_name='Motivo de la revisión'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='evaluaciones.equipo')),
            ],
            options={
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RunPython(motivo_de_las_ya_marcadas, sin_motivo),
    ]
