# Generated by Django 5.2.16 on 2026-08-19 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0015_evaluacion_motivo_revision_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='autor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por'),
        ),
    ]
