# Generated by Django 5.2.16 on 2026-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0016_incidencia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='autor_username',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='Registrada por (nombre guardado)'),
        ),
    ]
